package tm.binding.registry

enum EndpointType  {
   SAML_IDENTITY_PROVIDER,
   SAML_SERVICE_PROVIDER,
   OPENID_CONNECT_PROVIDER,
   OPENID_CONNECT_CLIENT,
   WEB_SERVICE_PROVIDER,
   WEB_SERVICE_CONSUMER
}

